language: python
python:
 - "2.7"

addons:
  apt:
    packages:
    - libpcap0.8-dev
    - libnetfilter-queue-dev
    - libssl-dev

notifications:
  irc: 
    channels:
      - "irc.freenode.org#MITMf"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} - %{commit_subject} : %{author}): %{message}"
    skip_join: true
    use_notice: true

install: "pip install -r requirements.txt"
before_script:
 - "pip install python-coveralls"
script: 
 - "nosetests --with-cov"
after_success:
 - coveralls
